version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wordle_db
      POSTGRES_PASSWORD: wordle_password
      POSTGRES_USER: wordle_user
    volumes: 
      - dbdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 20
      
    ports:
      - 5432:5432

  # app:
  #   build:
  #     context: server
  #     dockerfile: Dockerfile
  #   environment:
  #     DATABASE_URL: "postgresql://wordle_user:wordle_password@db:5432/mydb?schema=public"

  #   depends_on:
  #     db:
  #       condition: service_healthy

  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://wordle_user:wordle_password@db:5432/mydb?schema=public"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes: 
  dbdata:



